"""ajout external_series_key sur tournaments

Revision ID: 2a09835eff0f
Revises: 7af7cbf4ac30
Create Date: 2026-08-08 14:03:23.044924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a09835eff0f'
down_revision: Union[str, None] = '7af7cbf4ac30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('external_series_key', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_tournaments_external_series_key'), 'tournaments', ['external_series_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournaments_external_series_key'), table_name='tournaments')
    op.drop_column('tournaments', 'external_series_key')
    # ### end Alembic commands ###
