"""ajout is_qualification, points_raw, stat_won, stat_total

Revision ID: 7af7cbf4ac30
Revises: ab9d2052b0b0
Create Date: 2026-08-08 14:01:33.939824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7af7cbf4ac30'
down_revision: Union[str, None] = 'ab9d2052b0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_statistics', sa.Column('stat_won', sa.Integer(), nullable=True))
    op.add_column('match_statistics', sa.Column('stat_total', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('is_qualification', sa.Boolean(), nullable=False))
    op.add_column('matches', sa.Column('points_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'points_raw')
    op.drop_column('matches', 'is_qualification')
    op.drop_column('match_statistics', 'stat_total')
    op.drop_column('match_statistics', 'stat_won')
    # ### end Alembic commands ###
