"""schema initial

Revision ID: ab9d2052b0b0
Revises: 
Create Date: 2026-08-08 13:59:12.003265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab9d2052b0b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_raw_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingest_raw_log_method_fetched', 'ingest_raw_log', ['method', 'fetched_at'], unique=False)
    op.create_table('ingest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('api_calls_made', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('hand', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tour', sa.String(length=30), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=True),
    sa.Column('surface', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('prize_money', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('round_raw', sa.String(length=50), nullable=True),
    sa.Column('round_code', sa.String(length=10), nullable=True),
    sa.Column('player1_id', sa.Integer(), nullable=True),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_raw', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_raw', sa.String(length=50), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_player1_id'), 'matches', ['player1_id'], unique=False)
    op.create_index('ix_matches_player1_scheduled', 'matches', ['player1_id', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_matches_player2_id'), 'matches', ['player2_id'], unique=False)
    op.create_index('ix_matches_player2_scheduled', 'matches', ['player2_id', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_matches_scheduled_at'), 'matches', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_matches_tournament_id'), 'matches', ['tournament_id'], unique=False)
    op.create_table('player_external_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_player_source_external_id')
    )
    op.create_index(op.f('ix_player_external_ids_player_id'), 'player_external_ids', ['player_id'], unique=False)
    op.create_table('ranking_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('tour', sa.String(length=10), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('precision', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'tour', 'snapshot_date', 'source', name='uq_ranking_snapshot')
    )
    op.create_index(op.f('ix_ranking_snapshots_player_id'), 'ranking_snapshots', ['player_id'], unique=False)
    op.create_index(op.f('ix_ranking_snapshots_snapshot_date'), 'ranking_snapshots', ['snapshot_date'], unique=False)
    op.create_table('tournament_external_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_tournament_source_external_id')
    )
    op.create_index(op.f('ix_tournament_external_ids_tournament_id'), 'tournament_external_ids', ['tournament_id'], unique=False)
    op.create_table('match_external_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_match_source_external_id')
    )
    op.create_index(op.f('ix_match_external_ids_match_id'), 'match_external_ids', ['match_id'], unique=False)
    op.create_table('match_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('player1_games', sa.Integer(), nullable=True),
    sa.Column('player2_games', sa.Integer(), nullable=True),
    sa.Column('tiebreak_player1_points', sa.Integer(), nullable=True),
    sa.Column('tiebreak_player2_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'set_number', name='uq_match_set_number')
    )
    op.create_index(op.f('ix_match_sets_match_id'), 'match_sets', ['match_id'], unique=False)
    op.create_table('match_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('stat_period', sa.String(length=20), nullable=False),
    sa.Column('stat_name', sa.String(length=50), nullable=False),
    sa.Column('stat_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('raw_stat_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', 'stat_period', 'stat_name', name='uq_match_stat')
    )
    op.create_index(op.f('ix_match_statistics_match_id'), 'match_statistics', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_statistics_player_id'), 'match_statistics', ['player_id'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('selection', sa.String(length=50), nullable=False),
    sa.Column('odd_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_retroactive', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_odds_match_captured', 'odds_snapshots', ['match_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_match_id'), 'odds_snapshots', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odds_snapshots_match_id'), table_name='odds_snapshots')
    op.drop_index('ix_odds_match_captured', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index(op.f('ix_match_statistics_player_id'), table_name='match_statistics')
    op.drop_index(op.f('ix_match_statistics_match_id'), table_name='match_statistics')
    op.drop_table('match_statistics')
    op.drop_index(op.f('ix_match_sets_match_id'), table_name='match_sets')
    op.drop_table('match_sets')
    op.drop_index(op.f('ix_match_external_ids_match_id'), table_name='match_external_ids')
    op.drop_table('match_external_ids')
    op.drop_index(op.f('ix_tournament_external_ids_tournament_id'), table_name='tournament_external_ids')
    op.drop_table('tournament_external_ids')
    op.drop_index(op.f('ix_ranking_snapshots_snapshot_date'), table_name='ranking_snapshots')
    op.drop_index(op.f('ix_ranking_snapshots_player_id'), table_name='ranking_snapshots')
    op.drop_table('ranking_snapshots')
    op.drop_index(op.f('ix_player_external_ids_player_id'), table_name='player_external_ids')
    op.drop_table('player_external_ids')
    op.drop_index(op.f('ix_matches_tournament_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_scheduled_at'), table_name='matches')
    op.drop_index('ix_matches_player2_scheduled', table_name='matches')
    op.drop_index(op.f('ix_matches_player2_id'), table_name='matches')
    op.drop_index('ix_matches_player1_scheduled', table_name='matches')
    op.drop_index(op.f('ix_matches_player1_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('tournaments')
    op.drop_table('players')
    op.drop_table('ingest_runs')
    op.drop_index('ix_ingest_raw_log_method_fetched', table_name='ingest_raw_log')
    op.drop_table('ingest_raw_log')
    # ### end Alembic commands ###
